modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="abstract_antithesis" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Abstract Antithesis" #mandatory
# updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# logoFile="multiloader.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="Will BL" #optional
description='''
'''
[[dependencies.abstract_antithesis]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.abstract_antithesis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
